import { defaultBranchSettings, type MockDatabase } from "./domain.ts";
import { createDefaultPilotReadinessChecks } from "./pilot-readiness.ts";
import { createPaymentStatusHistoryEntry } from "./payment-lifecycle.ts";
import { defaultPilotPasswordHash } from "./pilot-password-contract.ts";

export { createDefaultPilotReadinessChecks } from "./pilot-readiness.ts";

function at(dayOffset: number, hour: number, minute = 0) {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  date.setDate(date.getDate() + dayOffset);
  return date.toISOString();
}

function dateOnly(dayOffset: number) {
  return at(dayOffset, 9).slice(0, 10);
}

function paymentHistory(status: MockDatabase["payments"][number]["status"], actorUserId: string, dayOffset: number, reason: string) {
  return [
    createPaymentStatusHistoryEntry({
      actorUserId,
      changedAt: at(dayOffset, 12),
      event: "created",
      reason,
      status,
    }),
  ];
}

function seededAuditLogs(): MockDatabase["auditLogs"] {
  return [
    {
      id: "audit-seed-attendance-update",
      branchId: "branch-gangnam",
      actorUserId: "user-coach",
      action: "attendance.update",
      targetType: "attendance",
      targetId: "att-jun-am",
      before: { status: "late" },
      after: { status: "present", confirmedAt: at(-1, 10, 8) },
      result: "success",
      message: "출석 상태를 변경했습니다.",
      createdAt: at(-1, 10, 8),
    },
    {
      id: "audit-seed-notice-create",
      branchId: "branch-gangnam",
      actorUserId: "user-owner",
      action: "notice.create",
      targetType: "notice",
      targetId: "notice-payment",
      before: null,
      after: { audience: ["owner", "guardian", "admin"], important: false },
      result: "success",
      message: "공지사항을 작성했습니다.",
      createdAt: at(-2, 16, 5),
    },
    {
      id: "audit-seed-branch-update",
      branchId: "branch-gangnam",
      actorUserId: "user-admin",
      action: "branch.update",
      targetType: "branch",
      targetId: "branch-gangnam",
      before: { status: "active" },
      after: { status: "active", timezone: "Asia/Seoul" },
      result: "success",
      message: "지점 운영 설정을 수정했습니다.",
      createdAt: at(-2, 13, 35),
    },
    {
      id: "audit-seed-payment-create",
      branchId: "branch-gangnam",
      actorUserId: "user-owner",
      action: "payment.create",
      targetType: "payment",
      targetId: "pay-seo",
      before: null,
      after: { amount: 150000, status: "expiringSoon" },
      result: "success",
      message: "회원권 결제를 등록했습니다.",
      createdAt: at(-3, 11, 20),
    },
    {
      id: "audit-seed-member-update",
      branchId: "branch-gangnam",
      actorUserId: "user-coach",
      action: "member.update",
      targetType: "member",
      targetId: "member-jun",
      before: { alerts: ["알레르기: 견과류"] },
      after: { alerts: ["알레르기: 견과류", "무릎 보호대 착용"] },
      result: "success",
      message: "회원 주의사항을 갱신했습니다.",
      createdAt: at(-4, 14, 10),
    },
    {
      id: "audit-seed-auth-login",
      branchId: null,
      actorUserId: "user-admin",
      action: "auth.login",
      targetType: "auth",
      targetId: "user-admin",
      before: null,
      after: { role: "admin" },
      result: "success",
      message: "로그인했습니다.",
      createdAt: at(-5, 9, 0),
    },
  ];
}

export function createMockData(): MockDatabase {
  return {
    branches: [
      {
        id: "branch-gangnam",
        name: "강남 본관",
        district: "서울 강남",
        settings: defaultBranchSettings,
        status: "active",
        timezone: "Asia/Seoul",
      },
      {
        id: "branch-songpa",
        name: "송파 도장",
        district: "서울 송파",
        settings: defaultBranchSettings,
        status: "active",
        timezone: "Asia/Seoul",
      },
    ],
    users: [
      {
        id: "user-admin",
        email: "admin@finaljudo.kr",
        name: "정유진",
        passwordHash: defaultPilotPasswordHash,
        phone: "01028476013",
        role: "admin",
        title: "총괄 운영 관리자",
        branchIds: ["branch-gangnam", "branch-songpa"],
      },
      {
        id: "user-owner",
        email: "owner@finaljudo.kr",
        name: "김도윤",
        phone: "01059274381",
        role: "owner",
        title: "2개 지점 대표",
        branchIds: ["branch-gangnam", "branch-songpa"],
      },
      {
        id: "user-coach",
        email: "coach@finaljudo.kr",
        name: "박서준",
        phone: "01031967428",
        role: "coach",
        title: "주니어/성인반 코치",
        branchIds: ["branch-gangnam"],
      },
      {
        id: "user-guardian",
        email: "guardian@finaljudo.kr",
        name: "이하린",
        phone: "01072483619",
        role: "guardian",
        title: "학부모",
        branchIds: ["branch-gangnam"],
        childMemberIds: ["member-jun", "member-seo", "member-yuna"],
      },
      {
        id: "user-songpa-guardian",
        email: "songpa.guardian@finaljudo.kr",
        name: "송지연",
        phone: "01081267345",
        role: "guardian",
        title: "학부모",
        branchIds: ["branch-songpa"],
        childMemberIds: ["member-harin"],
      },
      {
        id: "user-member",
        email: "member@finaljudo.kr",
        name: "최민재",
        phone: "01093645827",
        role: "member",
        title: "성인 회원",
        branchIds: ["branch-gangnam"],
        memberIds: ["member-minjae"],
      },
    ],
    members: [
      {
        id: "member-jun",
        branchId: "branch-gangnam",
        name: "이준",
        status: "active",
        ageGroup: "kids",
        level: "초급",
        belt: "노란띠",
        guardianIds: ["user-guardian"],
        primaryCoachId: "user-coach",
        emergencyContact: "010-7248-3619",
        alerts: ["알레르기: 견과류", "무릎 보호대 착용"],
        createdAt: at(-70, 14),
        statusChangedAt: at(-70, 14),
      },
      {
        id: "member-seo",
        branchId: "branch-gangnam",
        name: "이서",
        status: "active",
        ageGroup: "kids",
        level: "입문",
        belt: "흰띠",
        guardianIds: ["user-guardian"],
        primaryCoachId: "user-coach",
        emergencyContact: "010-7248-3619",
        alerts: [],
        createdAt: at(-42, 16),
        statusChangedAt: at(-42, 16),
      },
      {
        id: "member-minjae",
        branchId: "branch-gangnam",
        name: "최민재",
        status: "active",
        ageGroup: "adult",
        level: "중급",
        belt: "초록띠",
        guardianIds: [],
        primaryCoachId: "user-coach",
        emergencyContact: "010-9364-5827",
        alerts: ["손목 부상 회복 중"],
        createdAt: at(-95, 11),
        statusChangedAt: at(-95, 11),
      },
      {
        id: "member-yuna",
        branchId: "branch-gangnam",
        name: "한유나",
        status: "trial",
        ageGroup: "teen",
        level: "체험",
        belt: "흰띠",
        guardianIds: ["user-guardian"],
        primaryCoachId: "user-coach",
        emergencyContact: "010-6815-4072",
        alerts: [],
        createdAt: at(-5, 13),
        statusChangedAt: at(-5, 13),
      },
      {
        id: "member-jiho",
        branchId: "branch-gangnam",
        name: "오지호",
        status: "paused",
        ageGroup: "adult",
        level: "초급",
        belt: "노란띠",
        guardianIds: [],
        primaryCoachId: "user-coach",
        emergencyContact: "010-4579-2386",
        alerts: ["복귀 일정 조율 중"],
        createdAt: at(-120, 19),
        statusChangedAt: at(-12, 18),
      },
      {
        id: "member-harin",
        branchId: "branch-songpa",
        name: "송하린",
        status: "active",
        ageGroup: "kids",
        level: "초급",
        belt: "노란띠",
        guardianIds: ["user-songpa-guardian"],
        primaryCoachId: "user-admin",
        emergencyContact: "010-8126-7345",
        alerts: [],
        createdAt: at(-18, 15),
        statusChangedAt: at(-18, 15),
      },
    ],
    classes: [
      {
        id: "class-kids-am",
        branchId: "branch-gangnam",
        name: "유소년 유도 기초반",
        level: "입문-초급",
        ageGroup: "kids",
        coachId: "user-coach",
        startsAt: at(0, 10),
        endsAt: at(0, 10, 50),
        room: "매트 A",
        capacity: 12,
        enrolledMemberIds: ["member-jun", "member-seo"],
      },
      {
        id: "class-teen-pm",
        branchId: "branch-gangnam",
        name: "청소년 밸런스반",
        level: "체험-초급",
        ageGroup: "teen",
        coachId: "user-coach",
        startsAt: at(0, 17),
        endsAt: at(0, 17, 50),
        room: "매트 B",
        capacity: 10,
        enrolledMemberIds: ["member-yuna"],
      },
      {
        id: "class-adult-night",
        branchId: "branch-gangnam",
        name: "성인 직장인반",
        level: "초급-중급",
        ageGroup: "adult",
        coachId: "user-coach",
        startsAt: at(0, 20),
        endsAt: at(0, 21, 20),
        room: "매트 A",
        capacity: 16,
        enrolledMemberIds: ["member-minjae", "member-jiho"],
      },
      {
        id: "class-kids-tomorrow",
        branchId: "branch-gangnam",
        name: "유소년 낙법 집중반",
        level: "초급",
        ageGroup: "kids",
        coachId: "user-coach",
        startsAt: at(1, 16),
        endsAt: at(1, 16, 50),
        room: "매트 A",
        capacity: 12,
        enrolledMemberIds: ["member-jun", "member-seo"],
      },
      {
        id: "class-songpa-kids",
        branchId: "branch-songpa",
        name: "송파 유소년반",
        level: "초급",
        ageGroup: "kids",
        coachId: "user-admin",
        startsAt: at(0, 15),
        endsAt: at(0, 15, 50),
        room: "송파 매트",
        capacity: 10,
        enrolledMemberIds: ["member-harin"],
      },
    ],
    attendance: [
      {
        id: "att-jun-am",
        sessionId: "class-kids-am",
        memberId: "member-jun",
        status: "present",
        confirmedAt: at(0, 10, 8),
      },
      {
        id: "att-seo-am",
        sessionId: "class-kids-am",
        memberId: "member-seo",
        status: "late",
        confirmedAt: at(0, 10, 15),
      },
      {
        id: "att-minjae-night",
        sessionId: "class-adult-night",
        memberId: "member-minjae",
        status: "present",
        confirmedAt: at(0, 20, 4),
      },
    ],
    promotions: [],
    tournaments: [],
    counselingNotes: [
      {
        id: "note-jun-caution",
        branchId: "branch-gangnam",
        memberId: "member-jun",
        authorUserId: "user-coach",
        noteType: "caution",
        visibility: "coach_visible",
        body: "낙법 전 무릎 보호대 착용 확인. 견과류 알레르기 공유.",
        createdAt: at(-2, 17, 20),
      },
      {
        id: "note-jun-progress",
        branchId: "branch-gangnam",
        memberId: "member-jun",
        authorUserId: "user-coach",
        noteType: "progress",
        visibility: "guardian_visible",
        body: "낙법 후 일어서는 속도가 좋아졌고, 다음 수업은 발기술 연결을 연습합니다.",
        createdAt: at(-1, 18, 10),
      },
      {
        id: "note-seo-progress",
        branchId: "branch-gangnam",
        memberId: "member-seo",
        authorUserId: "user-coach",
        noteType: "progress",
        visibility: "guardian_visible",
        body: "앞구르기 진입 동작이 안정됨. 다음 수업에서 낙법 연결 연습 예정.",
        createdAt: at(-1, 18, 5),
      },
      {
        id: "note-minjae-staff",
        branchId: "branch-gangnam",
        memberId: "member-minjae",
        authorUserId: "user-owner",
        noteType: "follow_up",
        visibility: "staff_only",
        body: "손목 상태 확인 후 재등록 상담 필요.",
        createdAt: at(-3, 15, 30),
      },
    ],
    payments: [
      {
        id: "pay-jun",
        branchId: "branch-gangnam",
        memberId: "member-jun",
        planName: "유소년 주 3회권",
        status: "paid",
        amount: 180000,
        dueDate: dateOnly(20),
        expiresAt: dateOnly(35),
        statusHistory: paymentHistory("paid", "user-owner", -10, "수기 결제 등록"),
      },
      {
        id: "pay-seo",
        branchId: "branch-gangnam",
        memberId: "member-seo",
        planName: "유소년 주 2회권",
        status: "expiringSoon",
        amount: 150000,
        discountAmount: 10000,
        dueDate: dateOnly(5),
        expiresAt: dateOnly(6),
        statusHistory: paymentHistory("expiringSoon", "user-owner", -25, "회원권 만료 예정 상태 등록"),
      },
      {
        id: "pay-minjae",
        branchId: "branch-gangnam",
        memberId: "member-minjae",
        planName: "성인 월 회원권",
        status: "overdue",
        amount: 170000,
        discountAmount: 0,
        dueDate: dateOnly(-2),
        expiresAt: dateOnly(2),
        statusHistory: paymentHistory("overdue", "user-owner", -32, "미납 상태 확인"),
      },
      {
        id: "pay-yuna",
        branchId: "branch-gangnam",
        memberId: "member-yuna",
        planName: "체험권",
        status: "scheduled",
        amount: 30000,
        dueDate: dateOnly(1),
        expiresAt: dateOnly(7),
        statusHistory: paymentHistory("scheduled", "user-owner", -1, "체험권 납부 예정 등록"),
      },
      {
        id: "pay-harin",
        branchId: "branch-songpa",
        memberId: "member-harin",
        planName: "송파 유소년 주 2회권",
        status: "paid",
        amount: 150000,
        dueDate: dateOnly(25),
        expiresAt: dateOnly(40),
        statusHistory: paymentHistory("paid", "user-owner", -8, "송파 지점 수기 결제 등록"),
      },
    ],
    notices: [
      {
        id: "notice-promotion-result-jun",
        branchId: "branch-gangnam",
        title: "승급 심사 결과 안내",
        body: "노란띠 대상자는 낙법과 기본 잡기 기준을 통과했습니다. 보완 항목은 코치가 다음 피드백으로 안내합니다.",
        important: true,
        audience: ["guardian", "member"],
        createdAt: at(-1, 14),
        readByUserIds: [],
        targetMemberIds: ["member-jun"],
      },
      {
        id: "notice-youth-tournament",
        branchId: "branch-gangnam",
        title: "강남 유소년 교류전 대회 참가 안내",
        body: "참가 희망자는 보호자 확인 후 체급과 출전 가능 시간을 담당 코치에게 알려 주세요.",
        audience: ["guardian", "member"],
        createdAt: at(-1, 15),
        readByUserIds: [],
        targetMemberIds: ["member-jun", "member-seo"],
      },
      {
        id: "notice-summer",
        branchId: "branch-gangnam",
        title: "승급 심사 준비 안내",
        body: "심사 대상자는 출석률과 기본기 체크 항목을 담당 코치와 확인해 주세요.",
        important: true,
        audience: ["all"],
        createdAt: at(-1, 12),
        readByUserIds: ["user-owner"],
      },
      {
        id: "notice-payment",
        branchId: "branch-gangnam",
        title: "회원권 만료 안내",
        body: "만료 7일 전부터 결제 상태에서 확인하세요.",
        audience: ["owner", "guardian", "admin"],
        createdAt: at(-2, 16),
        readByUserIds: [],
      },
      {
        id: "notice-songpa",
        branchId: "branch-songpa",
        title: "송파 도장 매트 교체",
        body: "토요일 오전 수업은 매트 교체로 휴강합니다.",
        audience: ["all"],
        createdAt: at(-1, 10),
        readByUserIds: [],
      },
    ],
    authSessions: [],
    passwordResetChallenges: [],
    attendanceQrChallenges: [],
    pushSubscriptions: [],
    pushDispatchJobs: [],
    pilotReadinessChecks: createDefaultPilotReadinessChecks(),
    pilotIncidents: [],
    pilotOperationLogs: [],
    auditLogs: seededAuditLogs(),
  };
}
